# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('rating_average', models.FloatField(blank=True, null=True)),
                ('rating_stars', models.SmallIntegerField(blank=True, null=True)),
                ('collect_count', models.IntegerField(blank=True, null=True)),
                ('original_title', models.CharField(blank=True, max_length=200, null=True)),
                ('alt', models.URLField(blank=True, null=True)),
                ('douban_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('image_small', models.URLField(blank=True, null=True)),
                ('image_medium', models.URLField(blank=True, null=True)),
                ('image_large', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Country')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
    ]
