# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='boring',
            field=models.BooleanField(default=False),
        ),
    ]
