# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160131_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='douban_id',
        ),
    ]
