# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_boring'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
    ]
