# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_is_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_series',
            new_name='series',
        ),
    ]
