# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160131_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(),
        ),
    ]
