# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160130_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='douban_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
