# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20160131_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='douban_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
