# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20160131_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='douban_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
